spring:
  redis:
    #redis数据库索引(默认为0)
    database: 1
    #redis服务器地址
    host: 127.0.0.1
    #redis服务器连接端口
    port: 6379
    #redis连接密码1
    password:
    timeout: 8000
    jedis:
      pool:
        max-active: 300
        max-wait: 1ms
        min-idle: 300
