portal:
  token:
    # 设置为true后，token将存入redis，并具有单点登录功能 默认false使用JWT交互
    redis: true
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: true
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  mob:
    appKey: 你的appKey
  # 需要验证码校验的接口路径 支持通配符 自动过滤拦截校验 无需开发人员再次校验
  captcha:
    # 图片验证码验证
    filters:
      - /api/portal/auth/login # 登录接口
      - /api/portal/auth/register
  # 忽略鉴权url
  ignored:
    urls:
      - /captcha/init
      - /auth/register
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
